name: Ruff Autofix

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  ruff-format-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Specify your project's Python version

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff to fix and format
        run: |
          ruff format .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix(github-action): format and lint with ruff"
          commit_user_name: "matias-gabriel"
          commit_user_email: "matias.santos.mail@gmail.com"
          commit_author: "matias-gabriel <matias.santos.mail@gmail.com>"
